### ISSUE TITLE
SQLCipher version

### ISSUE THREAD

**Issue by MobiliteDev** [Milvintsiss/sqlite3_library_windows#1]
Thank you so much for your package with the dll.

Do you plan to bring SQLCipher version too one day ?

Do you also plan to explain how you have generated this dll with a readme ?

**Comment by Milvintsiss** [comment]
> Thank you so much for your package with the dll.

You're welcome, I'm happy this package helped you 🙂

> Do you plan to bring SQLCipher version too one day ?

No, I think SQLCipher deserves a package on its own, however I don't know much about it and I'm not able to help you for this. If you can have a dll of SQLCipher you are free to copy the code used in this package, the implementation should not defer a lot.

> Do you also plan to explain how you have generated this dll with a readme ?

I didn't generated any dll file, the dll present here is the 64-bit precompiled binary  from the [official website](https://www.sqlite.org/download.html)

**Comment by MobiliteDev** [comment]
Thank you for the answers
