### ISSUE TITLE
'DynamicLibrary? Function()' can't be assigned to the parameter type 'DynamicLibrary Function()'.dart(argument_type_not_assignable)

### ISSUE THREAD

**Issue by matthewkooshad** [Milvintsiss/sqlite3_library_windows#2]
The argument type 'DynamicLibrary? Function()' can't be assigned to the parameter type 'DynamicLibrary Function()'.dart(argument_type_not_assignable)
is the error i get when trying to use   open.overrideFor(OperatingSystem.windows, openSQLiteOnWindows); from the readme.

**Comment by Milvintsiss** [comment]
Thanks for reporting the issue,
I have just tested with the last version of `moor` package (`4.3.2`) and everything is working as expected so the error come from your config.

Your error (`argument_type_not_assignable`) seems to happen when imports are baddly formatted, imports should look as following:
```
import 'package:sqlite3/sqlite3.dart';
import 'package:sqlite3/open.dart';
import 'package:sqlite3_library_windows/sqlite3_library_windows.dart';
```
> Note that `dart:io` and `dart:ffi` are not required it's a doc error.

If this does not resolve the error please provide your `main.dart` file and your `pubspec.yaml`

**Comment by matthewkooshad** [comment]
![image](https://user-images.githubusercontent.com/6706761/123522357-6267e280-d682-11eb-8842-11b9284d379f.png)
so, i wasn't using import 'package:sqlite3/sqlite3.dart'; since it says unused. i don't see how you're using it with that open statement, so it makes sense to me that import 'package:sqlite3/sqlite3.dart'; is not needed. but, anyways, i put it in my main as you noted.
please see this image and note that i'm on flutter beta channel. it must be something on my side if you're using null safety version of flutter and the snippet works fine for you.

**Comment by Milvintsiss** [comment]
You need `sqlite3` import to load the dll file in memory.
```
final db = sqlite3.openInMemory();
db.dispose();
```

But no matter, the error come from my side, I always tested the lib with unsound null safety which allows operations like `DynamicLibrary Function() = DynamicLibrary? Function()`. (I did not see the `?` first time I looked to your issue sorry)

I will push a new version that should resolve the issue this evening or tomorrow 🙂

I will also write an example to test the package so this type of issue will not happen anymore.

**Comment by matthewkooshad** [comment]
that sounds awesome. i'll test and let you know once i hear it's ready for me to pub upgrade. thanks

**Comment by Milvintsiss** [comment]
It's published! Feel free to open a new issue if you have others problems using the package 🙂

**Comment by matthewkooshad** [comment]
thanks for the update:
Downloading sqlite3_library_windows 2.1.0...
Changed 1 dependency!
1 package has newer versions incompatible with dependency constraints.

and, i can confirm the example works for me on windows if i take the main dart and pubspec dependencies into a new fresh project.

**Comment by Milvintsiss** [comment]
Are you reporting an error here?
I assume you ran the `pub upgrade` command, 
the first two log lines:
```
Downloading sqlite3_library_windows 2.1.0...
Changed 1 dependency!
```
notify you that you successfully updated `sqlite3_library_windows` to the last version `2.1.0`.

The last log line:
```
1 package has newer versions incompatible with dependency constraints.
```
let you know that one of your package that you are depending on, cannot upgrade to his latest version because dependency conflicts with other packages or your environment constraints. However this has nothing to do with my lib because  `sqlite3_library_windows` have no dependency.

**Comment by matthewkooshad** [comment]
no error reporting here. I did create a thread over in moor though. I'm
unable to get moor isolate to work on windows

**Comment by Milvintsiss** [comment]
Ok so I assume you managed to load sqlite3, glad to here this and hope you will find a solution to your issue 🙂
