### ISSUE TITLE
using this and sqlite3_library_linux in the same code base

### ISSUE THREAD

**Issue by matthewkooshad** [Milvintsiss/sqlite3_library_windows#3]
i also found: https://pub.dev/packages/sqlite3_library_linux

i just wanted to ask, if you have a suggestion on how to use both this and sqlite3_library_linux in the same code base?

would i just have 2 lines alongside each other that would work depending on what's being built? i haven't tried this yet:
```dart
void main() {
  open.overrideFor(OperatingSystem.windows, openSQLiteOnWindows);
  open.overrideFor(OperatingSystem.linux, openSQLiteOnLinux);

  final db = sqlite3.openInMemory();
  db.dispose();
  
  runApp(MyApp());
}
```

**Comment by Milvintsiss** [comment]
Yes exactly! Your code snippet will work fine 🙂

Just wait for me to release a fix for linux as you will have the same issue that you encountered with sqlite3_library_windows. I will do it tomorrow and notify you in this thread.

**Comment by matthewkooshad** [comment]
ok, and thanks. but, no rush for me on the Linux one. just found it and
wanted to try it later on. thanks!

**Comment by Milvintsiss** [comment]
@matthewkooshad the new release for linux package is published.

As linux has plenty of distributions you will probably have issues with some of them, for now I can confirm it's working with Ubuntu 20.04 and Debian 10.

**Comment by matthewkooshad** [comment]
thanks!
